// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAviPaC0YQwJfNRXyTqD4Paph01LarAz4s',
    appId: '1:279927253519:web:55774d2db8e0495341d17a',
    messagingSenderId: '279927253519',
    projectId: 'trialog-8a95b',
    authDomain: 'trialog-8a95b.firebaseapp.com',
    storageBucket: 'trialog-8a95b.firebasestorage.app',
    measurementId: 'G-HBXYMMYQCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-m6SgJOMsySdYWCbwv_NUNPL8kbaZmSE',
    appId: '1:279927253519:android:bf9a23e6ebe5715641d17a',
    messagingSenderId: '279927253519',
    projectId: 'trialog-8a95b',
    storageBucket: 'trialog-8a95b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qyQNYhTAqG1VeNBqAhbE2HrfM3DNuPE',
    appId: '1:279927253519:ios:c9b943ad8dac8a9341d17a',
    messagingSenderId: '279927253519',
    projectId: 'trialog-8a95b',
    storageBucket: 'trialog-8a95b.firebasestorage.app',
    iosBundleId: 'com.example.trialog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7qyQNYhTAqG1VeNBqAhbE2HrfM3DNuPE',
    appId: '1:279927253519:ios:c9b943ad8dac8a9341d17a',
    messagingSenderId: '279927253519',
    projectId: 'trialog-8a95b',
    storageBucket: 'trialog-8a95b.firebasestorage.app',
    iosBundleId: 'com.example.trialog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAviPaC0YQwJfNRXyTqD4Paph01LarAz4s',
    appId: '1:279927253519:web:977063d001169d6541d17a',
    messagingSenderId: '279927253519',
    projectId: 'trialog-8a95b',
    authDomain: 'trialog-8a95b.firebaseapp.com',
    storageBucket: 'trialog-8a95b.firebasestorage.app',
    measurementId: 'G-HQF1TKWBSK',
  );
}
